[package]
name = "uloop"
version = "0.1.0"
authors = ["BroadLink"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
nix = "0.18"

